[project]
name = "todolist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromedriver-py==136.0.7103.113",
    "django>=5.2.1",
    "selenium>=4.33.0",
]
